### ISSUE TITLE
Question: what does fluent API mean in this context?

### ISSUE THREAD

**Issue by ecthiender** [hasura/graphql-data-specification#14]
> GDS is a fluent GraphQL API specification for transactional, analytical and streaming workloads across multiple data sources that contain semantically related data

Just a clarification question. Does the fluent here mean [this fluent interface](https://en.wikipedia.org/wiki/Fluent_interface)?

**Comment by coco98** [comment]
@ecthiender Good catch! Yeah, there are elements of chaining style composition that I wanted to convey, but it is more confusing than useful in this context. I'm removing it.
